---
- hosts:  all
  become: yes
  tasks:
  - name: Ensure apt dependencies are present
    apt:
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - virtualenv
      - nginx
      - git
  state: present
