---
- hosts:  all
  become: yes
- name: Ensure apt dependencies are present
  tasks:
    apt:
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - virtualenv
      - nginx
      - git
  state: present
